- name: install apt packages
  apt: "name='{{ item }}' state=present"
  with_items:
    - libmysqlclient-dev
    - unzip

- name: update the setuptools package to its latest version
  pip: 
    name: setuptools
    state: latest

- name: install the game server and its dependencies
  shell: python setup.py install
  args:
    chdir: "{{ game_server_directory }}"

- name: download ngrok archive to tmp folder
  shell: "wget {{ ngrok_download_url }}"
  args:
    chdir: /tmp/

- name: unzip ngrok to bin
  unarchive:
    src: "/tmp/{{ ngrok_download_url.split('/')[-1] }}"
    dest: /usr/bin/
    remote_src: True